### ISSUE TITLE
Make aktivatable/deactivatable by admin

### ISSUE THREAD

**Issue by ChristophWurst** [nickv-nextcloud/twofactor_nextcloud_notification#23]
This provider does not require any user interaction to get enabled/disabled, hence it would make sense to implement https://github.com/nextcloud/server/blob/master/lib/public/Authentication/TwoFactorAuth/IActivatableByAdmin.php and https://github.com/nextcloud/server/blob/master/lib/public/Authentication/TwoFactorAuth/IDeactivatableByAdmin.php for the provider. Then admins can enable it via 
```
php occ twofactorauth:enable user123 twofactor_nextcloud_notification
```

**Comment by nickvergessen** [comment]
Well you need another active session. If you don't have a sync client or mobile app connected, you could be locked out for ever :-X

**Comment by ChristophWurst** [comment]
@Gijom use https://apps.nextcloud.com/apps/twofactor_admin.

**Comment by Gijom** [comment]
This is indeed what I did, and it worked perfectly thanks. But still it is weird that disabling the 2auth from the command line does not work.

**Comment by ChristophWurst** [comment]
> But still it is weird that disabling the 2auth from the command line does not work.

Well, as the command told you, the operation is not implemented yet :wink:

**Comment by Happyfeet01** [comment]
Hello.

I logged out of the cloud and cant login anymore. The nextcloud App for iOS works (it has an app based key) can anyone help me?

**Comment by szaimen** [comment]
Any update on this? 
Would love to see this functionality.
Since `occ twofactorauth:disable <userID> twofactor_nextcloud_notification` is already implemented and working, `occ twofactorauth:enable <userID> twofactor_nextcloud_notification` is the only feature I am currently missing concerning this great app! And I see no problem related to a lockout since you can just disable it via occ for that user afterwards...
